services:
  # Backend service (Python Flask)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PORT=5000
    networks:
      - app-network
    

  # Frontend service (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000/api 
    networks:
      - app-network
    depends_on:
      - backend # Ensure backend is up before frontend

networks:
  app-network:
    driver: bridge