name: GitHubAction_Devops_Assigment

on:
  push:
  pull_request:

env:
  BACKEND_IMAGE_NAME: orosalesca/backend_assignment_api
  FRONTEND_IMAGE_NAME: orosalesca/frontend_assignment_react

jobs:
  build-and-push:
    name: Build, Test, and Push Docker Images
    runs-on: ubuntu-latest      
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          python-version: 3.9

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    

      # Build the backend Docker image
      - name: Build Backend Docker Image
        run: |
          docker build -t $BACKEND_IMAGE_NAME:latest ./backend

      # Test the backend image (optional: add a test script)
      - name: Test Backend Docker Image
        run: |
          docker run --rm -d --name backend-test -p 5000:5000 $BACKEND_IMAGE_NAME:latest
          # Add your tests here, e.g., curl to the app
          sleep 15 # Ensure container is running
          curl -f http://localhost:5000/api/test || (docker logs backend-test && exit 1)
          docker stop backend-test

      # Push the backend Docker image
      - name: Push Backend Docker Image
        run: |
          docker push $BACKEND_IMAGE_NAME:latest

      # Build the frontend Docker image
      - name: Build Frontend Docker Image
        run: |
          docker build -t $FRONTEND_IMAGE_NAME:latest ./frontend

      # Test the frontend image (optional: add a test script)
      - name: Test Frontend Docker Image
        run: |
          docker run --rm -d --name frontend-test -p 3000:3000 $FRONTEND_IMAGE_NAME:latest
          # Add your tests here, e.g., curl or HTTP request
          sleep 15 # Ensure container is running
          curl -f http://localhost:3000 || (docker logs frontend-test && exit 1)
          docker stop frontend-test    

      # Push the frontend Docker image
      - name: Push Frontend Docker Image
        run: |
          docker push $FRONTEND_IMAGE_NAME:latest    

          